version: '3.8'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: land-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:delegated
      - ../land-property-docker/docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: land-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ../land-property-docker/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-property}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-root}"
    networks:
        - laravel

  app:
    build:
      context: ../land-property-docker/docker
      dockerfile: Dockerfile
      args:
        # USER_NAME: "${USER_NAME:-www-data}"
        # USER_ID: "${USER_ID:-33}"
        # GROUP_ID: "${GROUP_ID:-33}"
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: land-php
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel